version: "3.9"
services:
  mqtt:
    build: .
    image: mqtt
    command: mosquitto -c /etc/mosquitto/mosquitto.conf
    container_name: 'mqtt-broker'
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - ./data:/data
    
